---

- name: Set service facts
  set_fact: nova_consoleauth_service="nova-consoleauth"
  when: ansible_os_family == 'Debian'

- name: Set service facts
  set_fact: nova_consoleauth_service="openstack-nova-console"
  when: ansible_os_family == 'RedHat'
