---

- name: Add datastax repo
  template: src=datastax.repo dest=/etc/yum.repos.d/datastax.repo

- name: Install Java
  yum: name=java-1.7.0-openjdk-headless state=present
  when: ansible_distribution_version.split(".")[0] == '7'

- name: Install Java
  yum: name=java-1.7.0-openjdk state=present
  when: ansible_distribution_version.split(".")[0] == '6'

- name: Install cassandra
  yum: name=cassandra20-2.0.10 state=present
  notify:
    - Stop cassandra

- meta: flush_handlers

- name: clear data
  shell: rm -rf /var/lib/cassandra

- name: Creates directory
  file: path=/var/lib/cassandra state=directory owner=cassandra group=cassandra mode=0775
