---

- name: Set service facts
  set_fact: nova_novncproxy_service="nova-novncproxy"
  when: ansible_os_family == 'Debian'

- name: Set service facts
  set_fact: nova_novncproxy_service="openstack-nova-novncproxy"
  when: ansible_os_family == 'RedHat'
