---
- name: Install MySQL packages
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
  when: ansible_distribution_version.split(".")[0] == '7'

- name: Install MySQL packages
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql
    - MySQL-python
  when: ansible_distribution_version.split(".")[0] == '6'

- name: Set facts
  set_fact: mysql_service=mariadb
  when: ansible_distribution_version.split(".")[0] == '7'

- name: Set facts
  set_fact: mysql_service=mysqld
  when: ansible_distribution_version.split(".")[0] == '6'

- name: Ensure MariaDB service is started and enabled
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Set mysql password
  shell: "mysqladmin -u root password {{ admin_password }}"
  ignore_errors: yes

- name: Add openstack mysql config
  copy: src=openstack.cnf dest=/etc/my.cnf.d/openstack.cnf
  notify:
    - Restart mysql
  when: ansible_distribution_version.split(".")[0] == '7'

- name: Add mysql config
  copy: src=my.cnf dest=/etc/my.cnf
  notify:
    - Restart mysql
  when: ansible_distribution_version.split(".")[0] == '6'

- name: Set MySQL max connections
  ini_file: dest=/etc/my.cnf section=mysqld option=max_connections value='1024'
  notify:
    - Restart mysql

- name: Set MySQL listen address
  ini_file: dest=/etc/my.cnf section=mysqld option=bind-address value={{ mgmt_ip }}
  notify:
    - Restart mysql
