---

- name: Set service facts
  set_fact: apache2_service="apache2"
  when: ansible_os_family == 'Debian'

- name: Set service facts
  set_fact: apache2_service="httpd"
  when: ansible_os_family == 'RedHat'

- name: Set dashboard settings facts
  set_fact: dashboard_settings="/etc/openstack-dashboard/local_settings.py"
  when: ansible_os_family == 'Debian'

- name: Set dashboard settings facts
  set_fact: dashboard_settings="/etc/openstack-dashboard/local_settings"
  when: ansible_os_family == 'RedHat'